---
title: "new_heatmap"
output: html_document
date: "2022-12-15"
---
Making new heatmaps with L2FC 
Comparisons by Group 
P0 vs P7
P0 vs P4
P0 vs P1 

```{r}
library(tidyr)
library(ggplot2)
```

Need to download the data in 
```{r}
P0_P1 <- read.csv("~/Documents/Mythreye_Lab/Mehri_Resha/anoikis/resLFC1_5_0vs1.csv")
P0_P4 <- read.csv("~/Documents/Mythreye_Lab/Mehri_Resha/anoikis/resLFC1_5_0vs4.csv")
P0_P7 <- read.csv("~/Documents/Mythreye_Lab/Mehri_Resha/anoikis/resLFC1_5_0vs7.csv")
```

```{r}
P0_P1_adj <- na.omit(P0_P1)
P0_P4_adj <- na.omit(P0_P4)
P0_P7_adj <- na.omit(P0_P7)
```

```{r}
P0_P1_adj2 <- P0_P1_adj[P0_P1_adj$padj <= .05 & P0_P1_adj$log2FoldChange >= 1.5, ]
P0_P1_adj3 <- P0_P1_adj[P0_P1_adj$padj <= .05 & P0_P1_adj$log2FoldChange <= -1.5, ]

P0_P4_adj2 <- P0_P4_adj[P0_P4_adj$padj <= .05 & P0_P4_adj$log2FoldChange >= 1.5, ]
P0_P4_adj3 <- P0_P4_adj[P0_P4_adj$padj <= .05 & P0_P4_adj$log2FoldChange <= -1.5, ]

P0_P7_adj2 <- P0_P7_adj[P0_P7_adj$padj <= .05 & P0_P7_adj$log2FoldChange >= 1.5, ]
P0_P7_adj3 <- P0_P7_adj[P0_P7_adj$padj <= .05 & P0_P7_adj$log2FoldChange <= -1.5, ]
```

So now we have a data frame for each up and down regulated set in each seq data set 
Now, we want to combine these and use the information to make a heatmap. 

```{r}
sigGenes <- as.list(c(P0_P1_adj2$X, P0_P1_adj3$X, P0_P4_adj2$X, P0_P4_adj3$X, P0_P7_adj2$X, P0_P7_adj3$X))
P0_P1_heatmap <- P0_P1[P0_P1$X %in% sigGenes,]
P0_P4_heatmap <- P0_P4[P0_P4$X %in% sigGenes,]
P0_P7_heatmap <- P0_P7[P0_P7$X %in% sigGenes,]

write.csv(P0_P1_heatmap, "~/Desktop/P0_P1_heatmap.csv")
write.csv(P0_P4_heatmap, "~/Desktop/P0_P4_heatmap.csv")
write.csv(P0_P7_heatmap, "~/Desktop/P0_P7_heatmap.csv")
```

```{r}
for_heatmap <- read.csv("~/Desktop/Heatmap_Groups_LogFC.csv")

for_heatmap_edit <- for_heatmap %>%
  pivot_longer(cols= c(P0_vs_P1, P0_vs_P4, P0_vs_P7), names_to = "time_point", values_to= "LFC"
)
```

```{r}
library(ggplot2)
library(scales) # needed for oob parameter
library(viridis)
library(RColorBrewer)
```


```{r}
heatmap <- ggplot(for_heatmap_edit, aes(x=time_point, y=X, fill=LFC)) + geom_raster() + scale_fill_distiller(palette = "RdBu") + theme(axis.text.x=element_text(angle=65, hjust=1), axis.text.y=element_blank(), axis.ticks.y=element_blank())
heatmap
```
