---
title: "Volcano_Plots_15U"
output: html_document
date: "2023-06-30"
---

```{r}
library(tximport)
library(GenomicFeatures)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(EnhancedVolcano)
library(org.Hs.eg.db)
library(biomaRt)
library(dplyr)
```

```{r}
P0_edit <- read.csv("~/Desktop/15U/res_P0_DMSO_vs_15U.csv")
P1_edit <- read.csv("~/Desktop/15U/res_P1_DMSO_vs_15U.csv")
P11_edit<- read.csv("~/Desktop/15U/res_P11_DMSO_vs_15U.csv")
```

```{r}
tx2gene <- select(txdb, k, "GENEID", "TXNAME")
grch38annot <- tx2gene %>% 
               dplyr::select(ensgene, symbol) %>% 
               dplyr::distinct()
```

```{r}
P0_genes <- gsub('\\.[0-9]*$','',P0_edit$X)
P1_genes <- gsub('\\.[0-9]*$','',P1_edit$X)
P11_genes <- gsub('\\.[0-9]*$','',P11_edit$X)
```

```{r}
ensembl <- useEnsembl(biomart = "genes")
```

```{r}
filters = listFilters(ensembl)
filters$name
```

```{r}
ensembl <- useDataset("hsapiens_gene_ensembl", mart=ensembl)
ensembl <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")
```

```{r}
P0_gene_symbol <- getBM(attributes = c("ensembl_gene_id", "hgnc_symbol"), 
      filters = "hgnc_symbol", 
      values = P0_genes, 
      mart = ensembl)
```


```{r}
P0 <- P0_edit[ , -1]
rownames(P0) <- P0_edit$X

P1 <- P1_edit[ , -1]
rownames(P1) <- P1_edit$X

P11 <- P11_edit[ , -1]
rownames(P11) <- P11_edit$X
```


```{r}
 EnhancedVolcano(res_6,
    lab = rownames(res_6),
    x = 'log2FoldChange',
    y = 'pvalue')
```