---
title: "GSVA_15U"
output: html_document
date: "2023-06-20"
---

Goals: individual passage #s and hallmarks for correlation based on individual time points 

```{r}
library("GSVA")
library(tidyr)
library(ggplot2)
library(scales) # needed for oob parameter
library(viridis)
library(reshape2)
library(data.table)
library(gtools)
library(org.Hs.eg.db)
```

```{r}
library(readr)
counts <- read.csv("~/RNAseq_Anoikis/OV90/RNAseq/15U/normalized_counts_15U.csv")
View(counts)
```

```{r}
no_decimals <- gsub('\\.[0-9]*$','',counts$X)
colnames(counts) <- c("X", "D01", "D02", "D03", "D11", "D12", "D13", "D111", "D112", "D113", "U01", "U02", "U03", "U11", "U12", "U13", "U111", "U112", "U113")
#now we are going to add this to the df 
counts$X <- no_decimals
counts <- counts[, 2:19]
rownames(counts) <- no_decimals
```

```{r}
counts2 <- as.matrix(counts)
```


#this is for the gene list that we are wanting for the Immune Signatures 
#same as from ClusterProfiler
```{r}
library("msigdbr")
library(enrichplot)
# we use ggplot2 to add x axis labels (ex: ridgeplot)
library(ggplot2)
library(cowplot)
# SET THE DESIRED ORGANISM HERE
organism = "org.Hs.eg.db"
#BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)
```

```{r echo=FALSE, message= FALSE, warning= FALSE}
#to get the gene set that we want
#in this particular setting we want the H genes, which are Hallmark genes 
h_gene_sets = msigdbr(species = "Homo sapiens", category = "H")
m_t2g <- msigdbr(species = "Homo sapiens", category = "H") %>% 
  dplyr::select(gs_name, ensembl_gene, human_entrez_gene)
```

```{r}
msigdbr_list = split(x = h_gene_sets$ensembl_gene, f = h_gene_sets$gs_name)
```

#running GSVA
```{r}
gsva.es <- gsva(counts2, msigdbr_list, method= "gsva", verbose=TRUE)
```

```{r}
write.csv(gsva.es, "~/RNAseq_Anoikis/OV90/RNAseq/15U/normalization_both_groups/Ov90_15U_Hallmarks_res_gsva.csv")
```

#heatmap to show the scores 
```{r}
data1 <- gsva.es
col.order <- c("D01", "D02", "D03", "U01", "U02", "U03", "D11", "D12", "D13", "U11", "U12", "U13", "D111", "D112", "D113", "U111", "U112", "U113")
data <-  data1[ , col.order]
```


```{r}
library(RColorBrewer)
coul <- brewer.pal(11, "RdBu") 
coul2 <- coul + scale_color_brewer(direction = -1)
library(ComplexHeatmap)
pdf("~/Desktop/heatmap_hallmarks_15U.pdf",width=8, height=11)
Heatmap(data, col = coul2, cluster_columns = FALSE, row_names_gp = gpar(fontsize = 4), )
dev.off()
```
