---
title: "Volcano_Plots_15U"
output: html_document
date: "2023-06-30"
---

```{r}
library(GenomicFeatures)
library(EnhancedVolcano)
library(org.Hs.eg.db)
library(dplyr)
```

```{r}
P0_GS <- read.csv("~/Desktop/15U/Gene_Symbol/res_P0_DMSO_vs_15U.csv")
P1_GS <- read.csv("~/Desktop/15U/Gene_Symbol/res_P1_DMSO_vs_15U.csv")
P11_GS <- read.csv("~/Desktop/15U/Gene_Symbol/res_P11_DMSO_vs_15U.csv")
P0_1_GS_DMSO <- read.csv("~/Desktop/15U/Gene_Symbol/P1_P0_DMSO.csv")
```


```{r}
EnhancedVolcano(P0_GS, lab = P0_GS$X, x = 'log2FoldChange', y = 'padj',   pCutoff= 0.5, FCcutoff = 1.5,  drawConnectors = TRUE, widthConnectors = 0.1, labSize= 2, max.overlaps= 100)
```

```{r}
ggsave("~/Desktop/volcano_P0_15U.png", plot=last_plot())
```

```{r}
EnhancedVolcano(P1_GS, lab = P1_GS$X, x = 'log2FoldChange', y = 'padj',   pCutoff= 0.5, FCcutoff = 1.5,  drawConnectors = TRUE, widthConnectors = 0.1, labSize= 2, max.overlaps= 100)
```

```{r}
ggsave("~/Desktop/volcano_P1_15U.png", plot=last_plot())
```

```{r}
EnhancedVolcano(P11_GS, lab = P11_GS$X, x = 'log2FoldChange', y = 'padj',   pCutoff= 0.5, FCcutoff = 1.5,  drawConnectors = TRUE, widthConnectors = 0.1, labSize= 2, max.overlaps= 100)
```

```{r}
ggsave("~/Desktop/volcano_P11_15U.png", plot=last_plot())
```

```{r}
EnhancedVolcano(P0_1_GS_DMSO, lab = P0_1_GS_DMSO$X, x = 'log2FoldChange', y = 'padj',   pCutoff= 0.5, FCcutoff = 1.5,  drawConnectors = TRUE, widthConnectors = 0.1, labSize= 2, max.overlaps= 100)
```

```{r}
ggsave("~/Desktop/volcano_P0_1_DMSO.png", plot=last_plot())
```